default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: hana1227
  host: localhost
  socket: /tmp/mysql.sock # Macでは通常このパスになります

development:
  <<: *default
  database: my_app_development

test:
  <<: *default
  database: my_app_test

production:
  <<: *default
  database: hair_counseling_production
  username: my_app
  password: my_app_password
  host: db
